baseURL = "/"
languageCode = "en-us"
title = "Subbagian Registrasi dan Statistik"
description = "An easy reading Hugo blog with night-mode."
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Nate Day"
    description = "Universitas Sultan Ageng Tirtayasa"
    logo = "favicon/untirta_192x190.png"
    twitterAuthor = "@natedayta"
    githubUsername = "tirtareg"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Berita"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Statistik"
    weight = 3
    
[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:registrasi@untirta.ac.id"
    name = "far fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://wa.me/6281311734542"
    name = "fab fa-whatsapp"
    weight = 2
