---
title: Penyesuaian UKT di Masa Pandemi Covid-19
author: masdian
date: '2021-02-18'
slug: penyesuaian-ukt-di-masa-pandemi-covid-19
categories: []
tags: []
---

> Sebelum melakukan pendaftaran penyesuaian UKT, perhatikan hal-hal berikut:
>
> 1.  Gunakan browser Mozilla Firefox
> 2.  Pastikan sudah login ke mail.google.com menggunakan akun email Untirta masing-masing pendaftar di Browser Mozilla Firefox
> 3.  Pendaftar WAJIB menggunakan akun email Untirta masing-masing (alamat email dan NIM harus sama)
> 4.  Jika lupa password email Untirta, silakan hubungi helpdesk Spada

1.  **Penangguhan pembayaran UKT**

    Kebijakan ini diperuntukan bagi mahasiswa yang **tidak mendapatkan Penyesuaian UKT** dan terkendala dengan pembayaran UKT sehingga memerlukan penangguhan
    pembayaran UKT. Bagi para pendaftar penangguhan pembayaran UKT diharapkan **memahami alur pengisian KRS** sehingga tidak terjadi masalah di kemudian hari. Alur pengisian KRS bagi mahasiswa yang melakukan penangguhan pembayaran UKT bisa dilihat [**di sini**](https://drive.google.com/file/d/1y9pSHwRBRkHsj_HRrLzvjg3xAsAVypVE/view?usp=sharing) dan formulir KRS manual bisa diunduh [**di sini**](https://drive.google.com/file/d/1yAM0GfI8bXYS2bw_Q6sRvMypzDFzgkdP/view?usp=sharing).

    Adapun berkas yang harus disiapkan dan diunggah adalah [**Surat Pernyataan Kesanggupan Membayar UKT**](https://drive.google.com/file/d/1wTfyJHu3QZsNu5QzvOjjo1oqr88CIkgJ/view?usp=sharing).

    Pendaftaran penangguhan pembayaran UKT dilakukan dengan mengisi formulir berikut **menggunakan akun email Untirta pendaftar** pada **08 - 10 Februari 2021**.
